name: Scheduled Task

on:
  schedule:
    - cron: "*/1 * * * *"  # Run every 5 minutes

jobs:
  my-scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "This job runs every 5 minutes!"
