name: Manual Workflow
env:
  MY_VAR: "This is a value for the entire workflow"
on:
  workflow_dispatch:

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Value of MY_VAR: $MY_VAR"
