name: Database Workflow new

on:
  workflow_dispatch

jobs:
  connect_to_database:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Connect to Database
        run: echo "Connecting to database at ${{secrets.DB_HOST}}"
        
      - name: Connect to Database2
        run: echo "Connecting to database at ${{vars.GREETING}}"
