name: Database Workflow new

on:
  workflow_dispatch

jobs:
  connect_to_database:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Database
        run: echo "Connecting to database at ${{secrets.DATABASE_PASSWORD}}"
